version: 0.2
env:
  secrets-manager:
    DEV_HOST: "arn:aws:secretsmanager:eu-central-1:868318271924:secret:development/ab-demo/postgresql-credentials-IAc9st:host"
    DEV_PORT: "arn:aws:secretsmanager:eu-central-1:868318271924:secret:development/ab-demo/postgresql-credentials-IAc9st:port"
    DEV_DATABASE: "arn:aws:secretsmanager:eu-central-1:868318271924:secret:development/ab-demo/postgresql-credentials-IAc9st:database"
    DEV_USER: "arn:aws:secretsmanager:eu-central-1:868318271924:secret:development/ab-demo/postgresql-credentials-IAc9st:user"
    DEV_PASSWORD: "arn:aws:secretsmanager:eu-central-1:868318271924:secret:development/ab-demo/postgresql-credentials-IAc9st:password"
    
    PROD_HOST: "arn:aws:secretsmanager:eu-central-1:868318271924:secret:production/ab-demo/postgresql-credentials-QzZs8S:host"
    PROD_PORT: "arn:aws:secretsmanager:eu-central-1:868318271924:secret:production/ab-demo/postgresql-credentials-QzZs8S:port"
    PROD_DATABASE: "arn:aws:secretsmanager:eu-central-1:868318271924:secret:production/ab-demo/postgresql-credentials-QzZs8S:database"
    PROD_USER: "arn:aws:secretsmanager:eu-central-1:868318271924:secret:production/ab-demo/postgresql-credentials-QzZs8S:user"
    PROD_PASSWORD: "arn:aws:secretsmanager:eu-central-1:868318271924:secret:production/ab-demo/postgresql-credentials-QzZs8S:password"
phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.4.1/flyway-commandline-8.4.1-linux-x64.tar.gz | tar xvz && ln -s `pwd`/flyway-8.4.1/flyway /usr/local/bin 
      - pip install psycopg2
  build:
    commands:
      - ls
      - cd scripts 
      #- python main.py
      - cd ..
      - ls
      #- cd temp
      - echo $GITHUB_EVENT_NAME
      - |
        if[[ $GITHUB_EVENT_NAME == "push" ]];
        then
          echo GITHUB_EVENT_NAME value is push
        else
          echo GITHUB_EVENT_NAME value is not push
        fi
     # - |
      #  if[$GITHUB_EVENT_NAME == "push"]
       # then
        #  echo Starting up migrate script...
         # chmod +x ./migrate.sh
          #./migrate.sh 
        #else
         # echo Starting up validate script...
          #chmod +x ./validate.sh
          #./validate.sh
      - echo $CODEBUILD_SOURCE_VERSION
  post_build:
   commands:
     - echo Entering post-build phase...
     - echo Build finished on `date`
