version: 0.2
env:
  secrets-manager:
    USER: "development/ab-demo/snowflake-credentials:user"
    PASSWORD: "development/ab-demo/snowflake-credentials:password"
    ACCOUNT: "development/ab-demo/snowflake-credentials:account"

phases:
  pre_build:
    commands:
      - export DEPLOYMENT_DTTM_UTC=$(date -u +%Y%m%d%H%M%S)
      - export DEPLOYMENT_DT_UTC=$(date -u +%Y%m%d)
      - echo Build started on $(date -u)
      - virtualenv venv
      - . venv/bin/activate
      - pip install --upgrade pip
      #- pip install -r https://raw.githubusercontent.com/snowflakedb/snowflake-connector-python/v2.6.2/tested_requirements/requirements_39.reqs
      #- pip install snowflake-connector-python==2.6.2
      - pip install ./scripts/lib/backout_functions_iolap-0.0.1-py3-none-any.whl
      - wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.4.1/flyway-commandline-8.4.1-linux-x64.tar.gz | tar xvz 1> /dev/null && ln -s `pwd`/flyway-8.4.1/flyway /usr/local/bin 
      - wget -q https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.33/slf4j-simple-1.7.33.jar -P ./flyway-8.4.1/lib/
  build:
    commands:
      - python ./scripts/make_flyway.py
      - echo Starting up flyway validate...
      - python ./scripts/run_flyway.py --validate
  post_build:
    commands:
      - zip -r artifacts.zip ab scripts buildspec.yml temp
      - aws s3 cp artifacts.zip s3://"$ARTIFACT_BUCKET"/"$DEPLOYMENT_DT_UTC"/"$DEPLOYMENT_DTTM_UTC"_"$GITHUB_SHA".zip
      - echo Entering post-build phase...
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" = "0" ]
        then exit 1
        fi
      - |
        if [ "$GITHUB_EVENT_NAME" = "push" ]
        then
          echo Starting up flyway migrate...
          python ./scripts/run_flyway.py --migrate
          if [ $? = 1 ]
            then sh ./temp/rollback.sh
          fi
          aws s3 cp artifacts.zip s3://"$ARTIFACT_BUCKET"/"$DEPLOYMENT_DT_UTC"/"$DEPLOYMENT_DTTM_UTC"_"$GITHUB_SHA".zip
        fi
      - echo Build finished on $(date -u)
# artifacts:
#   files:
#     - 'ab/**/*'
#     - 'scripts/**/*'
#     - 'temp/**/*'
#     - 'buildspec.yml'
#   name: artifact-"$DEPLOYMENT_DT_UTC"
#   s3-prefix: commitid
