CREATE OR REPLACE STAGE "EDP_LANDING"."LN_CICD_PIPELINE".AHRELJ01_STG_NODES
    URL = 's3://ahrelja-ab-demo/' 
    DIRECTORY = (ENABLE = TRUE)
    CREDENTIALS = (
      AWS_KEY_ID = 'AKIAWUTTTGMZJHVU3TGJ' 
      AWS_SECRET_KEY = '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'
    );