--  EDP_CONSUMER.DW_NCR."T_CUSTOMER360_MOCK_ACCOUNT" definition

CREATE TABLE "T_CUSTOMER360_MOCK_ACCOUNT" (
	USER_ID VARCHAR(63),
	ACCOUNT_ID VARCHAR(63),
	ACCOUNT_NUMBER VARCHAR(200),
	PRODUCT_UNIQUE_ID VARCHAR(63)
);


