--  EDP_CONSUMER.DW_NCR."T_MOCK_EPREFERENCES" definition

CREATE TABLE "T_MOCK_EPREFERENCES" (
	EPREFERENCE_ID VARCHAR(63) NOT NULL,
	ACCOUNT_ID VARCHAR(63) NOT NULL,
	EMAIL_ADDRESS VARCHAR(50) NOT NULL,
	DOC_TYPE VARCHAR(6) NOT NULL,
	PDF_PASSWORD VARCHAR(50),
	primary key (EPREFERENCE_ID)
);


