--  EDP_CONSUMER.DW_NCR."T_MOCK_STOP_CHECK" definition

CREATE TABLE "T_MOCK_STOP_CHECK" (
	UID VARCHAR(1024) NOT NULL,
	ACCT_ID VARCHAR(1024),
	ACCT_TYPE VARCHAR(1024),
	REC_TYPE VARCHAR(1024),
	CHECK_NUM VARCHAR(1024),
	CHECK_NUM_RANGE_END VARCHAR(1024),
	NAME VARCHAR(1024),
	AMOUNT DECIMAL(38,0),
	REASON_DESC VARCHAR(1024),
	REASON_CODE VARCHAR(1024),
	POSTED_DATE TIMESTAMP,
	STATUS_CODE VARCHAR(1024),
	primary key (UID)
);


