--  EDP_CONSUMER.DW_NCR."T_MOCK_ACCOUNT_PRODUCT" definition

CREATE TABLE "T_MOCK_ACCOUNT_PRODUCT" (
	ACCOUNT_PRODUCT_ID VARCHAR(63) NOT NULL,
	ACCOUNT_TYPE VARCHAR(2) NOT NULL,
	ACCOUNT_PRODUCT_NAME VARCHAR(127) NOT NULL,
	ACCOUNTING_CLASSIFICATION VARCHAR(1) NOT NULL,
	ACCOUNT_SOURCE VARCHAR(99) NOT NULL,
	MONEY_MOVEMENT_TYPE VARCHAR(20),
	primary key (ACCOUNT_PRODUCT_ID)
);


