--  EDP_CONSUMER.DW_NCR."T_USER_ACCOUNT_ELEMENT" definition

CREATE TABLE "T_USER_ACCOUNT_ELEMENT" (
	USER_ID VARCHAR(63),
	ACCOUNT_ID VARCHAR(63),
	ACTION VARCHAR(1024),
	EDP_LOAD_DTTM TIMESTAMP,
	EDP_DATA_DT DATE,
	EDP_RUN_ID DECIMAL(22,0)
);


