--  EDP_CONSUMER.DW_NCRUA."T_ABPZ05001_JSON" definition

CREATE TABLE "T_ABPZ05001_JSON" (
	EVENTS VARCHAR(256),
	EDP_DATA_DT DATE NOT NULL,
	EDP_LOAD_DTTM TIMESTAMP NOT NULL,
	EDP_RUN_ID DECIMAL(38,0) NOT NULL
);


