--  EDP_CONSUMER.DW_NCRUA."T_NEW_CUSTOMER_RT" definition

CREATE TABLE "T_NEW_CUSTOMER_RT" (
	ENTITY_ID DECIMAL(38,0) NOT NULL,
	ENT_MERGE_ID DECIMAL(38,0),
	INVOLVED_PARTY_ID VARCHAR(1024),
	FULL_NAME VARCHAR(1024),
	TAX_ID_TYPE_CODE VARCHAR(1024),
	TAX_ID_NUMBER VARCHAR(1024),
	DATE_OPENED DATE,
	IS_PROCESSED BOOLEAN,
	TIME_PROCESSED TIMESTAMP,
	EDP_LOAD_DTTM TIMESTAMP,
	EDP_DATA_DT DATE,
	EDP_RUN_ID DECIMAL(22,0),
	constraint PK_ENTITY_ID primary key (ENTITY_ID)
);


