--  EDP_CONSUMER.DW_NCRUA."T_USER_CONTACT" definition

CREATE TABLE "T_USER_CONTACT" (
	USER_ID VARCHAR(63),
	CONTACT_UNIQUE_ID VARCHAR(63) NOT NULL,
	CONTACT_TYPE VARCHAR(1024),
	LABEL VARCHAR(32),
	VALUE VARCHAR(1024),
	OUT_OF_BAND BOOLEAN,
	"PRIMARY" BOOLEAN,
	SMS BOOLEAN,
	VERIFICATION VARCHAR(1024),
	EDP_LOAD_DTTM TIMESTAMP,
	EDP_DATA_DT DATE,
	EDP_RUN_ID DECIMAL(22,0),
	constraint PK_CONTACT_UNIQUE_ID primary key (CONTACT_UNIQUE_ID)
);


