--  EDP_CONSUMER.DW_NCRUA."T_USER_ACCOUNT_ELEMENT" definition

CREATE TABLE "T_USER_ACCOUNT_ELEMENT" (
	USER_ID VARCHAR(63) NOT NULL,
	ACCOUNT_ID VARCHAR(63) NOT NULL,
	"ACTION" VARCHAR(1024),
	EDP_LOAD_DTTM TIMESTAMP,
	EDP_DATA_DT DATE,
	EDP_RUN_ID DECIMAL(22,0),
	constraint UAE_USER_ID unique (USER_ID),
	constraint UAE_ACCOUNT_ID unique (ACCOUNT_ID),
	constraint CPK_USER_ACCOUNT primary key (USER_ID, ACCOUNT_ID)
);


