--  EDP_CONSUMER.DW_NCRUA."T_USER_ACCOUNT_RELATIONSHIP_ATTRIBUTE" definition

CREATE TABLE "T_USER_ACCOUNT_RELATIONSHIP_ATTRIBUTE" (
	USER_ID VARCHAR(63),
	ATTRIBUTES VARCHAR(256),
	EDP_LOAD_DTTM TIMESTAMP,
	EDP_DATA_DT DATE,
	EDP_RUN_ID DECIMAL(22,0)
);


