--  EDP_CONSUMER.DW_NCRUA."T_NEW_ACCOUNT_RT" definition

CREATE TABLE "T_NEW_ACCOUNT_RT" (
	ACCOUNT_ID DECIMAL(38,0) NOT NULL,
	ACCT_NBR VARCHAR(1024),
	APPL_CD VARCHAR(1024),
	BANK_NBR VARCHAR(1024),
	DATE_OPENED DATE,
	IS_PROCESSED BOOLEAN,
	TIME_PROCESSED TIMESTAMP,
	EDP_LOAD_DTTM TIMESTAMP,
	EDP_DATA_DT DATE,
	EDP_RUN_ID DECIMAL(22,0),
	constraint PK_ACCOUNT_RT_ID primary key (ACCOUNT_ID)
);


