--  EDP_CONSUMER.DW_NCR."T_ABPZ05001_TRANSACTIONS_DEPOSIT" definition

CREATE TABLE "T_ABPZ05001_TRANSACTIONS_DEPOSIT" (
	"AZACTTYP_Account_Type" VARCHAR(1024),
	"AZACCT_Account_Nbr" DECIMAL(12,0),
	ACCOUNT_ID VARCHAR(63),
	TRANSACTION_ID VARCHAR(31),
	"AZALTYPE_Alert_Type" VARCHAR(1024),
	"AZDRCR_DR_CR_Code" VARCHAR(1024),
	"AZALAMT_Alert_Amount" DECIMAL(13,2),
	"AZCHECK_Check_Nbr" DECIMAL(15,0),
	"AZBAL_Account_Balance" DECIMAL(15,2),
	"AZDESC_Trans_Description" VARCHAR(1024),
	"AZHARDPOST_Hard_Post_Flag" VARCHAR(1024),
	"AZPGMID_Program_ID" VARCHAR(1024),
	"AZTMSTAMP_Alert_Timestamp" VARCHAR(1024),
	"AZMCC_Merchant_Code" DECIMAL(4,0),
	"AZMCNM_Merchant_Name" VARCHAR(1024),
	EDP_DATA_DT DATE,
	EDP_LOAD_DTTM TIMESTAMP,
	EDP_RUN_ID DECIMAL(38,0)
);


