--  EDP_CONSUMER.DW_NCR."USER_ACCOUNT_ELEMENT" definition

CREATE TABLE "USER_ACCOUNT_ELEMENT" (
	USER_ID VARCHAR(63),
	ACCOUNT_ID VARCHAR(63),
	ACTION VARCHAR(1024),
	constraint UFK_USER_ID unique (USER_ID),
	constraint UFK_ACCOUNT_ID unique (ACCOUNT_ID),
	constraint CPK_USER_ACCOUNT primary key (USER_ID, ACCOUNT_ID)
);


