--  EDP_CONSUMER.DW_PERSONETICS."COUNTRYCODE_CURRENCYCODE" definition

CREATE TABLE "COUNTRYCODE_CURRENCYCODE" (
	COUNTRY VARCHAR(1024),
	COUNTRYCODE VARCHAR(1024),
	CURRENCY VARCHAR(1024),
	CURRCODE VARCHAR(1024)
);


