--  EDP_CONSUMER.DW_PERSONETICS.T_RELATIONSHIP_TYPE_PER_XREF definition

CREATE TABLE T_RELATIONSHIP_TYPE_PER_XREF (
	FISERV_SIGNATURE_CODE VARCHAR(1024),
	DESCRIPTION VARCHAR(1024),
	TELEPHONE_BANKING_ONLINE_BANKING_ACCESS VARCHAR(1024),
	PERSONETICS_VOCABULARY_VALUE VARCHAR(1024)
);


