--  EDP_CONSUMER.DW_NCR.T_MOCK_EMPLOYMENT definition

CREATE TABLE T_MOCK_EMPLOYMENT (
	EMPLOYMENT_ID VARCHAR(63) NOT NULL,
	USER_ID VARCHAR(63) NOT NULL,
	ADDRESS_ID VARCHAR(63) NOT NULL,
	PROFESSION_CODE VARCHAR(3) NOT NULL,
	START_DATE DATE NOT NULL,
	YEARS_AT_JOB DECIMAL(38,0),
	EMAIL_ADDRESS VARCHAR(99),
	INCOME_AMOUNT DECIMAL(19,6),
	INCOME_SOURCE VARCHAR(1),
	primary key (EMPLOYMENT_ID)
);


