--  EDP_CONSUMER.DW_NCR.T_MOCK_PHONENUMBER definition

CREATE TABLE T_MOCK_PHONENUMBER (
	PHONE_NUMBER_ID VARCHAR(63) NOT NULL,
	USER_ID VARCHAR(63) NOT NULL,
	PHONE_TYPE VARCHAR(20) NOT NULL,
	PHONE VARCHAR(10) NOT NULL,
	PHONE_AVAILABLE_CODE VARCHAR(1),
	primary key (PHONE_NUMBER_ID)
);


