name: Push (Run CodeBuild)

on:
  workflow_dispatch:

jobs:
  sleep-two-minutes:
    name: run-codebuild-on-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
      
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
          
    - name: Sleep 2 mins
      run: sleep 2m
