#Check to ensure the latest main brach commit matches the new branches initial commit

name: Feature Branch Validation (1)

on:
  create:
    tags-ignore: '**'

jobs:
  branch-validation:
    runs-on: ubuntu-latest
    steps:     
      - name: Checkout Production
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: production

      - name: Setup environment variables
        run: |
          echo "DEV_TAG=dev-${{ github.ref_name }}" >> $GITHUB_ENV
          echo "LAST_PROD_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate branch is branched off of Production or off of dev-tag
        run: |
          if [[ -z $(git branch ${{ github.ref_name }} --contains ${{ env.LAST_PROD_SHA }}) ]];
          then 
            echo "Feature branch != production. ${{ github.ref_name }} is not branched off of Production"

            if [[ -z $(git branch ${{ github.ref_name }} --contains ${{ env.DEV_TAG }} 2> /dev/null) ]];
            then
              echo "Feature branch ${{ github.ref_name }} is invalid. Delete in progress"
              git push origin --delete ${{ github.ref_name }}
            else
              echo "Feature branch ${{ github.ref_name }} is recreated using tag: ${{ env.DEV_TAG }}"
            fi
            
          else
            echo "Feature branch == production. ${{ github.ref_name }} is branched off of Production and is valid"
          
          fi
