name: Delete Feature Branch

on:
 delete:
   tags-ignore: '**'

jobs:
  delete_feature_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Development Branch
        uses: actions/checkout@v2
        with:
          ref: development
          fetch-depth: 0
      
      - name: Setup environment variables
        run: |
          echo "DEV_TAG=dev-${{ github.event.ref }}" >> $GITHUB_ENV
          echo "PROD_TAG=prod-${{ github.event.ref }}" >> $GITHUB_ENV
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Validate deleted branch
        run: |
          FEATURE_BRANCH_TAGS="${{ env.DEV_TAG }} ${{ env.PROD_TAG }}"

          ALL_TAGS_FOUND=true
          NO_TAGS_FOUND=true

          for tag in $FEATURE_BRANCH_TAGS;
          do
            if [[ -z $(git branch development --contains $tag 2> /dev/null) ]];
            then ALL_TAGS_FOUND=false
            else NO_TAGS_FOUND=false
            fi
          done
      
          if [[ "$ALL_TAGS_FOUND" == true && "$NO_TAGS_FOUND" == false ]];
            then echo 'Feature branch contains both dev and prod tags; Delete ${{ github.event.ref }} branch'
          elif [[ "$ALL_TAGS_FOUND" == false && "$NO_TAGS_FOUND" == true ]];
            then echo 'Feature branch does not contain dev or prod tags; Delete ${{ github.event.ref }} branch'
          else
            echo 'Branch $DEV_TAG was not supposed to be deleted. Delete reverted'
            git checkout -b ${{ github.event.ref }} $DEV_TAG
            git push origin ${{ github.event.ref }}
          fi
