name: PR Open/Sync Validation

on:
  pull_request:
    branches: [development, production]
    types: [opened, synchronize]

jobs:
  pr-opened-synchronize:
    name: pr-opened-synchronize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Feature
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
          
      - name: Setup environment variables
        run: |
          echo "DEV_TAG=dev-${{ github.head_ref }}" >> $GITHUB_ENV
          echo "TAGGED_COMMIT_ID=$(git rev-list dev-${{ github.head_ref }} -n 1 2> /dev/null)" >> $GITHUB_ENV
      
      - name: Validate Lower Environment Tags Exist
        if: ${{ github.base_ref == 'production' }}
        run: |
          if [ -z ${{ env.TAGGED_COMMIT_ID }} ]; 
          then
            echo "Lower Environment (development) tag (${{ env.DEV_TAG }}) does not exist"
            exit 1
          else 
            echo "Lower Environment (development) tag (${{ env.DEV_TAG }}) exists: ${{ env.TAGGED_COMMIT_ID }}"
          fi
      
      - name: Validate Lower Environment Tag = Feature branch HEAD
        if: ${{ github.base_ref == 'production' }}
        run: |
          FEATURE_BRANCH_LAST_COMMIT=${{ github.event.pull_request.head.sha }}
                    
          if [ "$FEATURE_BRANCH_LAST_COMMIT" = ${{ env.TAGGED_COMMIT_ID }} ];
          then 
            echo "Feature branch HEAD = Tagged COMMIT_ID"
          else 
            echo "Feature branch HEAD is not = Tagged COMMIT_ID"
            exit 1
          fi
  
#  pr-opened-run-codebuild:
#    name: pr-opened-run-codebuild
#    runs-on: ubuntu-latest
#    needs: pr-opened-synchronize
#    steps:
#    - name: Checkout Feature
#      uses: actions/checkout@v2
#      with:
#        token: ${{ secrets.TOKEN }}
#    
#    - name: Configure AWS Credentials
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: us-east-1
#
#    - name: Run CodeBuild
#      uses: aws-actions/aws-codebuild-run-build@v1
#      with:
#        project-name: CodeBuildProject-0HmCLmrCTbsZ
#        buildspec-override: ./buildspec.yml
#        env-vars-for-codebuild: |
#          ENVIRONMENT,
#          GITHUB_EVENT_ACTION_NAME
#      env:
#       ENVIRONMENT: ${{ github.base_ref }}
#       GITHUB_EVENT_ACTION_NAME: ${{ github.event.action }}
#
