name: "Testing workflow"

on:
  #workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SLEEP_INTERVAL: 10

jobs:
  check-existing-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ env.GH_TOKEN }}
          fetch-depth: 0
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Wait for existing workflows to complete
        run: |
          while true; do
            RUNNING_WORKFLOWS=$(gh run list --branch ${{ github.head_ref }} --json databaseId,name,status --jq '.[] | select((.name=="${{ github.workflow }}") and (.status=="in_progress") and (.databaseId<${{ github.run_id }}))')
            echo "$(date) Running workflows:"
            echo $RUNNING_WORKFLOWS
            if [ -z "$RUNNING_WORKFLOWS" ]; 
            then
              break
            fi
            sleep ${{ env.SLEEP_INTERVAL }}
          done
          
      #- name: Close PR
      #  run: |
      #    gh pr merge ${{ github.event.number }} --squash
      #    PR_CLOSE_RUN_ID=$(gh run list --branch ${{ github.event.pull_request.base.ref }} --json databaseId,status,name --jq '.[] | select((.status=="in_progress") and (.name=="PR Close Validation")) | .databaseId')
      #    gh run watch $PR_CLOSE_RUN_ID --exit-status
    
  sleep-one-minute:
    runs-on: ubuntu-latest
    needs: check-existing-runs
    steps:
      - name: Sleep for 60 seconds
        run: sleep 60
