name: "Testing workflow"

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  sleep-minute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
        
      - name: Check for running Workflows
        run: |
          BRANCH_NAME=$(${{ github.ref }} | sed -r 's|refs/heads/||g')
          RUNNING_WORKFLOWS=$(gh run list --branch $BRANCH_NAME --json conclusion,createdAt,databaseId,event,headBranch,name,status,workflowDatabaseId --jq '.[] | select((.name=="${{ github.workflow }}") and (.status=="in_progress") and (.databaseId!=${{ github.run_id }}))')
          echo $RUNNING_WORKFLOWS
      
      - name: Sleep for 60 seconds
        run: sleep 60
