name: Remote

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: git remote -v
        
      - name: Checkout Production
        uses: actions/checkout@v3
        with:
          ref: production
          repository: sukyca/snowflake-test-repo
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0

      - name: Run a one-line script
        run: git remote -v
