name: "Testing workflow"

on:
  workflow_dispatch:
  #pull_request:
  #  types: [opened, synchronize]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_CONTEXT: ${{ toJSON(github) }}
  SLEEP_INTERVAL: 10

jobs:
  check-existing-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ env.GH_TOKEN }}
          fetch-depth: 0
      
      - name: Dump GitHub context
        run: echo "${{ env.GITHUB_CONTEXT }}"
        
      - name: Turnstyle
        id: turnstyle
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: ${{ env.SLEEP_INTERVAL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  sleep-one-minute:
    runs-on: ubuntu-latest
    needs: check-existing-runs
    steps:
      - name: Sleep for 60 seconds
        run: sleep 60
