name: Tests Trigger Workflow

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true
    
    inputs:
      TESTING_FEATURE_BRANCH:
        required: false
        type: string
        default: feature/testing-branch
  
  workflow_dispatch:
    inputs:
      TESTING_FEATURE_BRANCH:
        required: false
        type: string
        default: feature/testing-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Checkout Production
        uses: actions/checkout@v3
        with:
          ref: production
          repository: sukyca/demo-auto-tag
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
        
      - name: Print commit logs
        run: git log --oneline -n 10
        
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git fetch origin

          git remote add upstream https://github.com/sukyca/snowflake-test-repo.git
          git fetch upstream
          git merge upstream/production --allow-unrelated-histories --strategy-option theirs
          git branch -u origin/production
          
          git checkout --track origin/development
          git merge upstream/development --allow-unrelated-histories --strategy-option theirs
          git branch -u origin/development

          git checkout --track origin/${{ inputs.TESTING_FEATURE_BRANCH }}
          echo "cehckout"
          git merge upstream/${{ inputs.TESTING_FEATURE_BRANCH }} --allow-unrelated-histories --strategy-option theirs
          echo "merge"
          git push -u origin ${{ inputs.TESTING_FEATURE_BRANCH }}
          echo "push"
          git log --oneline -n 10
          
