name: "Testing workflow"

on:
  pull_request:
    types: [opened, synchronize]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_CONTEXT: ${{ toJSON(github) }}
  SLEEP_INTERVAL: 10

jobs:
  sleep-minute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ env.GH_TOKEN }}
          fetch-depth: 0
      
      - name: Dump GitHub context
        run: echo "${{ env.GITHUB_CONTEXT }}"
        
      - name: Check for running Workflows
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed -r 's|refs/heads/||g')
          
          while true; do
            RUNNING_WORKFLOWS=$(gh run list 
              --branch $BRANCH_NAME 
              --json conclusion,createdAt,databaseId,event,headBranch,name,status,workflowDatabaseId 
              --jq '.[] | select(
                  (.name=="${{ github.workflow }}") 
                  and (.status=="in_progress") 
                  and (.databaseId!=${{ github.run_id }}))'
            )
            echo "$(date) Running workflows:"
            echo $RUNNING_WORKFLOWS
            if [ -z "$RUNNING_WORKFLOWS" ]; 
            then
              break
            fi
            sleep ${{ env.SLEEP_INTERVAL }}
          done
      
      - name: Sleep for 60 seconds
        run: sleep 60
