name: Workflow1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      token: ${{ secrets.S_TOKEN }}

    steps:
      - name: Checkout Production
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
          ref: production
          
      - name: Trigger the Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.S_TOKEN }}" "https://api.github.com/repos/sukyca/demo-auto-tag/dispatches" -d "{\"event_type\":\"Workflow2\",\"client_payload\":{\"unit\":false,\"integration\":true}}" 