name: Test workflows

on:
  workflow_dispatch:

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Production
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 1
          ref: production
      - name: Run tests for workflows
        run: |
          ls 
