name: Test workflows

on:
  workflow_dispatch:

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Production
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
          ref: production
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Run tests for workflows
        run: |
          ls 
          cd python
          chmod -R +x workflow_test_scripts
          git commit -a --allow-empty-message -m ''
          cd workflow_test_scripts
          ./test-1-f.sh & PID=$!
          wait $PID
          ./test-1-s.sh & PID=$!
          wait $PID
          ./test-2-f.sh & PID=$!
          wait $PID
          ./test-2-s.sh & PID=$!
          wait $PID
          ./test-3-s.sh & PID=$!
          wait $PID
          ./test-4-f.sh & PID=$!
          wait $PID
          ./test-4-s.sh & PID=$!
          wait $PID